# Generated by Django 4.2 on 2026-03-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_machine_machine_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Máy móc', 'verbose_name_plural': 'Máy móc'},
        ),
        migrations.AlterModelOptions(
            name='maintenancehistory',
            options={'verbose_name': 'Lịch sử bảo trì', 'verbose_name_plural': 'Lịch sử bảo trì'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AlterModelOptions(
            name='repairrequest',
            options={'verbose_name': 'Yêu cầu sửa chữa', 'verbose_name_plural': 'Yêu cầu sửa chữa'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='classification_level',
            field=models.IntegerField(choices=[(1, 'Cấp 1'), (2, 'Cấp 2'), (3, 'Cấp 3')], default=1, verbose_name='Phân cấp'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã máy'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(default='hiep', max_length=200, verbose_name='Tên máy'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('working', 'Hoạt động'), ('broken', 'Hỏng'), ('maintenance', 'Đang bảo trì/sửa chữa')], default='working', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='action_taken',
            field=models.TextField(verbose_name='Hành động đã thực hiện'),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chi phí'),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày thực hiện'),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine', verbose_name='Máy móc'),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kỹ thuật viên'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(0, 'Chờ duyệt'), (1, 'Cấp 1'), (2, 'Cấp 2'), (3, 'Cấp 3 - Quản lý cao nhất')], default=0, verbose_name='Cấp quyền'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='description',
            field=models.TextField(verbose_name='Mô tả sự cố'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine', verbose_name='Máy móc'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang sửa'), ('done', 'Đã hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái yêu cầu'),
        ),
    ]
